name: Build, Push and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  detect-changes:
    name: Detect Changed Applications
    runs-on: ubuntu-latest

    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      # frontend: ${{ steps.filter.outputs.frontend }}
      frontend_ang: ${{ steps.filter.outputs.frontend_ang }}
      shared: ${{ steps.filter.outputs.shared }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'apps/api_v2/**'

            # frontend:
            #   - 'apps/e-comm/**'

            frontend_ang:
              - 'apps/angular-ecomm/**'

            shared:
              - 'packages/ui/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'turbo.json'

  ################################################################################
  # BACKEND
  ################################################################################

  backend:
    name: Build Backend
    needs: detect-changes

    if: |
      needs.detect-changes.outputs.backend == 'true' ||
      needs.detect-changes.outputs.shared == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        run: |
          docker build \
            -f apps/api_v2/Dockerfile \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }} \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_BACKEND_REPO }}:latest \
            .

      - name: Push Backend Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_BACKEND_REPO }}:latest

  ################################################################################
  # REACT
  ################################################################################

  # frontend:
  #   name: Build React Frontend
  #   needs: detect-changes

  #   if: |
  #     needs.detect-changes.outputs.frontend == 'true' ||
  #     needs.detect-changes.outputs.shared == 'true'

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - uses: aws-actions/amazon-ecr-login@v2

  #     - name: Build React Image
  #       run: |
  #         docker build \
  #           -f apps/e-comm/Dockerfile \
  #           -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }} \
  #           -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO }}:latest \
  #           .

  #     - name: Push React Image
  #       run: |
  #         docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }}
  #         docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO }}:latest

  ################################################################################
  # ANGULAR
  ################################################################################

  angular:
    name: Build Angular Frontend
    needs: detect-changes

    if: |
      needs.detect-changes.outputs.frontend_ang == 'true' ||
      needs.detect-changes.outputs.shared == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build Angular Image
        run: |
          docker build \
            -f apps/angular-ecomm/Dockerfile \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO_ANG }}:${{ github.sha }} \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO_ANG }}:latest \
            .

      - name: Push Angular Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO_ANG }}:${{ github.sha }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO_ANG }}:latest

  ################################################################################
  # DEPLOY BACKEND
  ################################################################################

  deploy-backend:
    name: Deploy Backend
    needs: [detect-changes, backend]

    if: |
      needs.detect-changes.outputs.backend == 'true' ||
      needs.detect-changes.outputs.shared == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          aws ecs describe-task-definition \
            --task-definition ${{ secrets.BACKEND_TASK_DEFINITION }} \
            --query taskDefinition \
            > task-definition.json

      - run: |
          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )' task-definition.json > cleaned.json

          mv cleaned.json task-definition.json

      - id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          service: ${{ secrets.BACKEND_SERVICE }}
          wait-for-service-stability: true

  ################################################################################
  # DEPLOY REACT
  ################################################################################

  # deploy-frontend:
  #   name: Deploy React
  #   needs: [detect-changes, frontend]

  #   if: |
  #     needs.detect-changes.outputs.frontend == 'true' ||
  #     needs.detect-changes.outputs.shared == 'true'

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - run: |
  #         aws ecs describe-task-definition \
  #           --task-definition ${{ secrets.FRONTEND_TASK_DEFINITION }} \
  #           --query taskDefinition \
  #           > task-definition.json

  #     - run: |
  #         jq 'del(
  #           .taskDefinitionArn,
  #           .revision,
  #           .status,
  #           .requiresAttributes,
  #           .compatibilities,
  #           .registeredAt,
  #           .registeredBy
  #         )' task-definition.json > cleaned.json

  #         mv cleaned.json task-definition.json

  #     - id: task-def
  #       uses: aws-actions/amazon-ecs-render-task-definition@v1
  #       with:
  #         task-definition: task-definition.json
  #         container-name: ${{ secrets.FRONTEND_CONTAINER_NAME }}
  #         image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }}

  #     - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
  #       with:
  #         task-definition: ${{ steps.task-def.outputs.task-definition }}
  #         cluster: ${{ secrets.ECS_CLUSTER }}
  #         service: ${{ secrets.FRONTEND_SERVICE }}
  #         wait-for-service-stability: true

  ################################################################################
  # DEPLOY ANGULAR
  ################################################################################

  deploy-angular:
    name: Deploy Angular
    needs: [detect-changes, angular]

    if: |
      needs.detect-changes.outputs.frontend_ang == 'true' ||
      needs.detect-changes.outputs.shared == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          aws ecs describe-task-definition \
            --task-definition ${{ secrets.ANGULAR_FRONTEND_TASK_DEFINITION }} \
            --query taskDefinition \
            > task-definition.json

      - run: |
          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )' task-definition.json > cleaned.json

          mv cleaned.json task-definition.json

      - id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ secrets.ANGULAR_FRONTEND_CONTAINER_NAME }}
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO_ANG }}:${{ github.sha }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          service: ${{ secrets.ANGULAR_FRONTEND_SERVICE }}
          wait-for-service-stability: true
